# Generated by Django 3.2 on 2021-05-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('inst_email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('instructor_fname', models.CharField(max_length=40)),
                ('instructor_lname', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(db_column='org_ID', primary_key=True, serialize=False)),
                ('org_name', models.CharField(db_column='org_Name', max_length=100)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=60)),
                ('student_fname', models.CharField(max_length=40)),
                ('student_lname', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
