# Generated by Django 3.2 on 2021-05-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=0, max_digits=10)),
                ('access_scorefunction', models.DecimalField(db_column='access_ScoreFunction', decimal_places=0, max_digits=10)),
                ('initial_pop', models.IntegerField()),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
    ]
