# Generated by Django 3.2 on 2021-05-24 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessid', models.AutoField(primary_key=True, serialize=False)),
                ('immunization_perc', models.IntegerField(blank=True, default=100)),
                ('EDUSmoking_perc', models.IntegerField(blank=True, default=100)),
                ('EDUDisease_perc', models.IntegerField(blank=True, default=100)),
                ('Screening_perc', models.IntegerField(blank=True, default=100)),
                ('TestingLab_perc', models.IntegerField(blank=True, default=100)),
                ('TestingPharmo_perc', models.IntegerField(blank=True, default=100)),
                ('AnnualPCP_perc', models.IntegerField(blank=True, default=100)),
                ('HospitalCare_perc', models.IntegerField(blank=True, default=100)),
                ('MentalHealth_perc', models.IntegerField(blank=True, default=100)),
                ('EmergencyCare_perc', models.IntegerField(blank=True, default=100)),
                ('OutPatientSurg_perc', models.IntegerField(blank=True, default=100)),
                ('OutPatientRadio_perc', models.IntegerField(blank=True, default=100)),
                ('PhysicianPCP_perc', models.IntegerField(blank=True, default=100)),
                ('PhysicianSpec_perc', models.IntegerField(blank=True, default=100)),
                ('UrgentCare_perc', models.IntegerField(blank=True, default=100)),
                ('HomeHealth_perc', models.IntegerField(blank=True, default=100)),
                ('Hospice_perc', models.IntegerField(blank=True, default=100)),
                ('LTAC_perc', models.IntegerField(blank=True, default=100)),
                ('SkilledNursing_perc', models.IntegerField(blank=True, default=100)),
                ('NursingHome_perc', models.IntegerField(blank=True, default=100)),
                ('AsstLiving_perc', models.IntegerField(blank=True, default=100)),
                ('IndLiving_perc', models.IntegerField(blank=True, default=100)),
                ('NameBrand_perc', models.IntegerField(blank=True, default=100)),
                ('GenDrugs_perc', models.IntegerField(blank=True, default=100)),
                ('SpecialtyDrugs_perc', models.IntegerField(blank=True, default=100)),
                ('DurableMedEqu_perc', models.IntegerField(blank=True, default=100)),
                ('TobTax_perc', models.IntegerField(blank=True, default=0)),
                ('Alcohol_perc', models.IntegerField(blank=True, default=0)),
                ('FattyFoods_perc', models.IntegerField(blank=True, default=0)),
                ('SugFoods_perc', models.IntegerField(blank=True, default=0)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.AutoField(primary_key=True, serialize=False)),
                ('join_tag', models.CharField(default=1, max_length=100, unique=True)),
                ('game_name', models.CharField(db_column='game_name', max_length=100)),
                ('initial_population', models.IntegerField(default=0)),
                ('initial_budget', models.IntegerField(default=0)),
                ('Instructor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game',
                'managed': True,
            },
        ),
    ]
