# Generated by Django 3.2 on 2021-05-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_newmigration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='sessid',
            new_name='sessionid',
        ),
    ]
