# Generated by Django 3.2 on 2021-05-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('prefix', models.CharField(max_length=40)),
                ('credit_hours', models.IntegerField()),
                ('course_num', models.CharField(max_length=40)),
                ('section_num', models.CharField(max_length=40)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'course_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(db_column='org_ID', primary_key=True, serialize=False)),
                ('org_name', models.CharField(db_column='org_Name', max_length=100)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionid', models.AutoField(primary_key=True, serialize=False)),
                ('prev_expenses', models.IntegerField(blank=True, null=True)),
                ('acute_expenses', models.IntegerField(blank=True, null=True)),
                ('ambul_expenses', models.IntegerField(blank=True, null=True)),
                ('long_expenses', models.IntegerField(blank=True, null=True)),
                ('pharm_expenses', models.IntegerField(blank=True, null=True)),
                ('tax_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
    ]
