# Generated by Django 3.2 on 2021-05-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_sessid_session_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='game_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
