# Generated by Django 3.2 on 2021-05-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210525_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='Alcohol_perc',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='session',
            name='FattyFoods_perc',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='session',
            name='SugFoods_perc',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='session',
            name='TobTax_perc',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
    ]
