# Generated by Django 3.2 on 2021-05-27 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_session_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='game_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hostgame', to='game.game'),
        ),
    ]
