# Generated by Django 3.2 on 2021-05-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_session_game_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='course',
        ),
        migrations.AddField(
            model_name='game',
            name='course',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
