# Generated by Django 3.2 on 2021-06-08 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210527_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='initial_budget',
            field=models.DecimalField(decimal_places=2, default=150000000, max_digits=13, verbose_name=django.core.validators.MinValueValidator(150000000)),
        ),
        migrations.AlterField(
            model_name='game',
            name='join_tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
