# Generated by Django 3.2 on 2021-06-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210608_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='join_tag',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
