# Generated by Django 3.2 on 2021-06-08 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_game_join_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='initial_budget',
            field=models.DecimalField(decimal_places=2, default=150000000, max_digits=13, validators=[django.core.validators.MinValueValidator(150000000)]),
        ),
    ]
