# Generated by Django 3.2 on 2021-06-25 18:17

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20210625_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deadline',
            field=models.DateField(default=game.models.Game.return_date_time),
        ),
    ]
