# Generated by Django 3.2 on 2021-05-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=60)),
                ('student_fname', models.CharField(max_length=40)),
                ('student_lname', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
