# Generated by Django 3.2 on 2021-05-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('prefix', models.CharField(max_length=40)),
                ('credit_hours', models.IntegerField()),
                ('course_num', models.CharField(max_length=40)),
                ('section_num', models.CharField(max_length=40)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'course_section',
                'managed': True,
            },
        ),
    ]
