# Generated by Django 3.2 on 2021-05-23 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='credit_hours',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='crn',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.coursesection')),
                ('instructor', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class',
                'managed': True,
            },
        ),
    ]
